### ISSUE TITLE
`omg gcp` Creates Bad Manifest

### ISSUE THREAD

**Issue by cholick** [enaml-ops/omg-cli#42]
Using the most recent release (1.0.1), the `omg gcp` command creates an un-deployable manifest. The `cloud_provider` section's template is missing a name:

```
cloud_provider:
  template: {name: "", release: bosh-google-cpi}
```

Deploy fails with:
```
Command 'deploy' failed:
  Parsing installation manifest ...:
    Validating installation manifest:
      cloud_provider.template.name must be provided
```

Invoked with:
```
omg gcp \
    --bosh-private-ip some-value \
    --gcp-network-name some-value \
    --gcp-subnetwork-name some-value \
    --gcp-default-zone some-value \
    --gcp-project some-value
```

**Comment by xchapter7x** [comment]
@cholick , thanks for reporting this. GCP functionality needs some love as it hasn't had its legs stretched much yet.

the fix to your issue is found in commit: https://github.com/enaml-ops/omg-cli/commit/f9a4a35f7151d392c92990719a9a1c0051f6b07b

and can be used by downloading the latest release: https://github.com/enaml-ops/omg-cli/releases/tag/v1.0.2
